import { LibTableColumnDefinition } from "@solar-lib";

export interface WashRecord {
    readonly id: number;
    readonly isSpecial: boolean;
    readonly rate: number; // between 0 and 1
    readonly canBeDeleted: boolean;
    readonly customer: string;
}

export const washColumns: LibTableColumnDefinition<WashRecord>[] = [
    {id: 'name', header: 'לקוח', width: { basis: 200, grow: 2 }, value: rec => rec.customer },
    {id: 'special', header: 'מיוחד', width: 100, value: rec => rec.isSpecial ? 1 : 0 },
    {id: 'rate', header: 'דירוג', width: {basis: 100, grow: 1}, value: rec => rec.rate },
    {id: 'actions', header: 'פעולות', width: 150 }
]


export const washesData: WashRecord[] = [
    { id: 482651, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'דוד כהן' },
    { id: 739284, isSpecial: true, rate: 1, canBeDeleted: false, customer: 'רחל לוי' },
    { id: 156923, isSpecial: false, rate: 0.45, canBeDeleted: true, customer: 'יוסף מזרחי' },
    { id: 892147, isSpecial: true, rate: 0, canBeDeleted: false, customer: 'שרה ביטון' },
    { id: 543876, isSpecial: false, rate: 0.78, canBeDeleted: true, customer: 'משה אברהם' },
    { id: 218543, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'מרים פרץ' },
    { id: 976234, isSpecial: true, rate: 0.23, canBeDeleted: true, customer: 'אברהם חיים' },
    { id: 345678, isSpecial: false, rate: 0.67, canBeDeleted: false, customer: 'ליאה שמעון' },
    { id: 654321, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'יצחק דהן' },
    { id: 123789, isSpecial: true, rate: 1, canBeDeleted: true, customer: 'דינה עזרא' },
    { id: 789456, isSpecial: false, rate: 0.34, canBeDeleted: false, customer: 'אליהו מלכה' },
    { id: 456123, isSpecial: false, rate: 0.89, canBeDeleted: true, customer: 'חנה אוחיון' },
    { id: 234567, isSpecial: true, rate: 0, canBeDeleted: false, customer: 'שלמה ששון' },
    { id: 876543, isSpecial: false, rate: 0.56, canBeDeleted: true, customer: 'אסתר בוזגלו' },
    { id: 543219, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'דניאל עמר' },
    { id: 198765, isSpecial: true, rate: 0.12, canBeDeleted: true, customer: 'תמר בן דוד' },
    { id: 765432, isSpecial: false, rate: 0.91, canBeDeleted: false, customer: 'עמוס סעדון' },
    { id: 321654, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'נעמי אלבז' },
    { id: 987123, isSpecial: true, rate: 0.43, canBeDeleted: false, customer: 'בנימין ברוך' },
    { id: 654987, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'רות מימון' },
    { id: 147258, isSpecial: false, rate: 0.76, canBeDeleted: false, customer: 'גדעון חדד' },
    { id: 852963, isSpecial: true, rate: 0, canBeDeleted: true, customer: 'יעל זוהר' },
    { id: 369258, isSpecial: false, rate: 0.28, canBeDeleted: false, customer: 'אריאל שלום' },
    { id: 741852, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'מיכל סבג' },
    { id: 963741, isSpecial: true, rate: 0.65, canBeDeleted: false, customer: 'אליעזר טולדנו' },
    { id: 258147, isSpecial: false, rate: 0.82, canBeDeleted: true, customer: 'שולמית עטיה' },
    { id: 159753, isSpecial: false, rate: 0, canBeDeleted: false, customer: 'נתן אמסלם' },
    { id: 357951, isSpecial: true, rate: 0.47, canBeDeleted: true, customer: 'פנינה אזולאי' },
    { id: 753159, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'יעקב בוחבוט' },
    { id: 951357, isSpecial: false, rate: 0.19, canBeDeleted: true, customer: 'שרה בן שושן' },
    { id: 486271, isSpecial: true, rate: 0.73, canBeDeleted: false, customer: 'מרדכי סימון' },
    { id: 172648, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'חוה אבוטבול' },
    { id: 826714, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'ראובן כרמי' },
    { id: 617482, isSpecial: true, rate: 0.54, canBeDeleted: true, customer: 'זהבה אלון' },
    { id: 284617, isSpecial: false, rate: 0.38, canBeDeleted: false, customer: 'שמעון בן חמו' },
    { id: 714826, isSpecial: false, rate: 0.86, canBeDeleted: true, customer: 'דבורה נחמני' },
    { id: 482716, isSpecial: true, rate: 0, canBeDeleted: false, customer: 'אהרן שוקרון' },
    { id: 126748, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'שושנה יצחקי' },
    { id: 847261, isSpecial: false, rate: 0.61, canBeDeleted: false, customer: 'חיים בן שמעון' },
    { id: 261847, isSpecial: true, rate: 0, canBeDeleted: true, customer: 'רבקה סעד' },
    { id: 748126, isSpecial: false, rate: 0.25, canBeDeleted: false, customer: 'אברהם בן עמי' },
    { id: 916284, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'מלכה חזן' },
    { id: 284916, isSpecial: true, rate: 0.72, canBeDeleted: false, customer: 'צבי בן יוסף' },
    { id: 629184, isSpecial: false, rate: 0.41, canBeDeleted: true, customer: 'גילה קורן' },
    { id: 184629, isSpecial: false, rate: 0, canBeDeleted: false, customer: 'אשר אברג׳ל' },
    { id: 462918, isSpecial: true, rate: 0.88, canBeDeleted: true, customer: 'אורה בן חיים' },
    { id: 918462, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'מנחם לוגסי' },
    { id: 573829, isSpecial: false, rate: 0.33, canBeDeleted: true, customer: 'עדנה שטרית' },
    { id: 829573, isSpecial: true, rate: 0, canBeDeleted: false, customer: 'יורם מזוז' },
    { id: 295738, isSpecial: false, rate: 0.69, canBeDeleted: true, customer: 'אילנה כהנא' },
    { id: 738295, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'אלי חיון' },
    { id: 385729, isSpecial: true, rate: 0.51, canBeDeleted: true, customer: 'ברכה בוחניק' },
    { id: 729385, isSpecial: false, rate: 0.14, canBeDeleted: false, customer: 'נפתלי בן צבי' },
    { id: 957238, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'יפה אלקיים' },
    { id: 238957, isSpecial: true, rate: 0.79, canBeDeleted: false, customer: 'שמואל ממן' },
    { id: 895723, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'חיה בן שלום' },
    { id: 723895, isSpecial: false, rate: 0.46, canBeDeleted: false, customer: 'זאב בן עטיה' },
    { id: 457239, isSpecial: true, rate: 0, canBeDeleted: true, customer: 'דליה מרציאנו' },
    { id: 239457, isSpecial: false, rate: 0.84, canBeDeleted: false, customer: 'יהושע שושן' },
    { id: 794523, isSpecial: false, rate: 0.37, canBeDeleted: true, customer: 'שירה ברזילי' },
    { id: 523794, isSpecial: true, rate: 1, canBeDeleted: false, customer: 'רפאל אדרי' },
    { id: 347952, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'נורית עמית' },
    { id: 952347, isSpecial: false, rate: 0.62, canBeDeleted: false, customer: 'בועז אלפסי' },
    { id: 274395, isSpecial: true, rate: 1, canBeDeleted: true, customer: 'טובה סולומון' },
    { id: 395274, isSpecial: false, rate: 0.29, canBeDeleted: false, customer: 'גרשון אילוז' },
    { id: 527439, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'נחמה בן ארי' },
    { id: 439527, isSpecial: true, rate: 0.75, canBeDeleted: false, customer: 'יונתן כחלון' },
    { id: 759243, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'גאולה משה' },
    { id: 243759, isSpecial: false, rate: 0.58, canBeDeleted: false, customer: 'עזרא בן חמדה' },
    { id: 592437, isSpecial: true, rate: 0, canBeDeleted: true, customer: 'סיגלית בנאי' },
    { id: 437592, isSpecial: false, rate: 0.21, canBeDeleted: false, customer: 'מנשה צדוק' },
    { id: 924375, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'פרידה אלוש' },
    { id: 375924, isSpecial: true, rate: 0.68, canBeDeleted: false, customer: 'חגי בן משה' },
    { id: 759342, isSpecial: false, rate: 0.42, canBeDeleted: true, customer: 'עליזה גבאי' },
    { id: 342759, isSpecial: false, rate: 0, canBeDeleted: false, customer: 'שמחה אוזן' },
    { id: 597324, isSpecial: true, rate: 0.81, canBeDeleted: true, customer: 'צפורה שמש' },
    { id: 324597, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'לוי סמואל' },
    { id: 792345, isSpecial: false, rate: 0.36, canBeDeleted: true, customer: 'עינת מושקט' },
    { id: 345792, isSpecial: true, rate: 0, canBeDeleted: false, customer: 'חנוך סויסה' },
    { id: 927543, isSpecial: false, rate: 0.93, canBeDeleted: true, customer: 'יפית אסולין' },
    { id: 543927, isSpecial: false, rate: 1, canBeDeleted: false, customer: 'אפרים חמו' },
    { id: 275943, isSpecial: true, rate: 0.17, canBeDeleted: true, customer: 'אביבה בנימין' },
    { id: 943275, isSpecial: false, rate: 0.52, canBeDeleted: false, customer: 'איתן בן מיכאל' },
    { id: 752943, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'סימה אוחנה' },
    { id: 943752, isSpecial: true, rate: 0.71, canBeDeleted: false, customer: 'אורי בן הרוש' },
    { id: 529437, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'רונית שלו' },
    { id: 437529, isSpecial: false, rate: 0.26, canBeDeleted: false, customer: 'אסף בוקובזה' },
    { id: 925734, isSpecial: true, rate: 0, canBeDeleted: true, customer: 'גרציה זריהן' },
    { id: 734925, isSpecial: false, rate: 0.64, canBeDeleted: false, customer: 'נחום אליהו' },
    { id: 257349, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'ורדה מלכה' },
    { id: 349257, isSpecial: true, rate: 0.48, canBeDeleted: false, customer: 'קלמן בן סעדון' },
    { id: 927345, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'שלומית זוהר' },
    { id: 345927, isSpecial: false, rate: 0.85, canBeDeleted: false, customer: 'בצלאל עזר' },
    { id: 729543, isSpecial: true, rate: 1, canBeDeleted: true, customer: 'אלישבע שמואל' },
    { id: 543729, isSpecial: false, rate: 0.31, canBeDeleted: false, customer: 'אביגדור מלול' },
    { id: 927534, isSpecial: false, rate: 0, canBeDeleted: true, customer: 'צילה רוזנבלום' },
    { id: 534927, isSpecial: true, rate: 0.77, canBeDeleted: false, customer: 'פנחס אבוקרט' },
    { id: 729345, isSpecial: false, rate: 1, canBeDeleted: true, customer: 'לאה חביב' }
]